name: revolution
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # http
  dio: ^4.0.6
  # dio_cookie_manager: ^1.0.0
  # cookie_jar: ^1.0.1
  retrofit: ^3.3.1
  json_annotation: ^4.8.0
  # http: ^0.12.2

  # state
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  shared_preferences: ^2.0.6

  # date
  date_format: ^2.0.0
  intl: ^0.16.1

  # function
  flutter_local_notifications: ^6.0.0
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.3.5
  local_auth: ^0.6.3+4
  vector_math: ^2.0.8
  flutter_vibrate: ^1.0.0
  # vibration: ^1.7.3
  # flutter_tapjoy: ^1.2.3+2
  # tap_joy_plugin: ^0.0.7

  # ui
  fluttertoast: ^7.1.8
  flutter_svg: ^0.19.1
  sticky_headers: ^0.1.8+1
  scratcher: ^1.4.2
  video_player: ^1.0.1
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^2.3.0
  loading_indicator: ^1.2.0
  loading_animations: ^2.1.0
  modal_bottom_sheet: ^1.0.0+1
  palette_generator: ^0.2.3
  webview_flutter: ^2.7.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  json_serializable: 6.6.0
  retrofit_generator: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/home/
    - assets/components/
