name: btrips
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  retrofit: ^1.3.4+1
  json_annotation: ^3.1.1

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  shared_preferences: ^0.5.12+4

  date_format: ^1.0.9
  intl: ^0.16.1
  flutter_local_notifications: ^4.0.1+2

  qr_flutter: ^3.2.0

  fluttertoast: ^7.1.8
  flutter_svg: ^0.19.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.9
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.1
  retrofit_generator: ^1.4.1+3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
